({
	doInit : function(component, event, helper) {
        var jsonData = JSON.parse(helper.getSampleJSON());
        console.log(jsonData); 
        component.set("v.gridData",jsonData);
	},
    getSampleJSON : function(){
     return '{"rows":[{"vals":[{"val":"Pipeline","cssClass":""},{"val":"","cssClass":""},{"val":"","cssClass":""},{"val":"","cssClass":"responsiveHide"},{"val":"","cssClass":"responsiveHide"},{"val":"","cssClass":"responsiveHide"},{"val":"","cssClass":"responsiveHide"},{"val":"","cssClass":"responsiveHide"},{"val":"","cssClass":"responsiveHide"},{"val":"400,000","cssClass":"responsiveHide"},{"val":"400,000","cssClass":"responsiveHide"},{"val":"400,000","cssClass":"responsiveHide"},{"val":"400,000","cssClass":"responsiveHide"}]},{"vals":[{"val":"Wins","cssClass":""},{"val":"1,000,000","cssClass":"responsiveHide"},{"val":"1,000,000","cssClass":"responsiveHide"},{"val":"1,000,000","cssClass":"responsiveHide"},{"val":"1,000,000","cssClass":"responsiveHide"},{"val":"1,000,000","cssClass":"responsiveHide"},{"val":"1,000,000","cssClass":"responsiveHide"},{"val":"1,000,000","cssClass":"responsiveHide"},{"val":"10,000","cssClass":"responsiveHide"},{"val":"","cssClass":"responsiveHide"},{"val":"","cssClass":"responsiveHide"},{"val":"","cssClass":""}]},{"vals":[{"val":"Losses","cssClass":""},{"val":"5,000","cssClass":""},{"val":"2,000","cssClass":"responsiveHide"},{"val":"100,000","cssClass":"responsiveHide"},{"val":"5,000,000","cssClass":"responsiveHide"},{"val":"5,000","cssClass":"responsiveHide"},{"val":"2,000","cssClass":"responsiveHide"},{"val":"1,00,000","cssClass":"responsiveHide"},{"val":"5,000,000","cssClass":"responsiveHide"},{"val":"","cssClass":"responsiveHide"},{"val":"","cssClass":"responsiveHide"},{"val":"","cssClass":"responsiveHide"}]}],"headers":[{"title":"Metric","isSortable":false,"dataType":"","cssClass":"responsiveHide"},{"title":"Apr-20","isSortable":false,"dataType":"","cssClass":""},{"title":"May-20","isSortable":false,"dataType":"","cssClass":""},{"title":"Jun-20","isSortable":false,"dataType":"","cssClass":""},{"title":"Jul-20","isSortable":false,"dataType":"","cssClass":"responsiveHide"},{"title":"Aug-20","isSortable":false,"dataType":"","cssClass":"responsiveHide"},{"title":"Sep-20","isSortable":false,"dataType":"","cssClass":"responsiveHide"},{"title":"Oct-20","isSortable":false,"dataType":"","cssClass":"responsiveHide"},{"title":"Nov-20","isSortable":false,"dataType":"","cssClass":"responsiveHide"},{"title":"Dec-20","isSortable":false,"dataType":"","cssClass":"responsiveHide"},{"title":"Jan-21","isSortable":false,"dataType":"","cssClass":"responsiveHide"},{"title":"Feb-21","isSortable":false,"dataType":"","cssClass":"responsiveHide"},{"title":"Mar-21","isSortable":false,"dataType":"","cssClass":"responsiveHide"}]}';
    }
})